  apiVersion: v1
  kind: Service
  metadata:
    name: f5-demo-service
    labels:
      name: f5-demo-app-route
    namespace: f5demo
  spec:
    type: ClusterIP
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      app: f5-demo-app-route

---

  apiVersion: v1
  kind: Service
  metadata:
    name: f5-demo-app-route-2
    labels:
      name: f5-demo-app-route
    namespace: f5demo
  spec:
    type: ClusterIP
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      app: f5-demo-app-route

---

  apiVersion: v1
  kind: Service
  metadata:
    name: f5-demo-app-route-3
    labels:
      name: f5-demo-app-route
    namespace: f5demo
  spec:
    type: ClusterIP
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      app: f5-demo-app-route
